name: Backend CI/CD

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install required packages

      - name: Run tests
        run: |
          pytest  # Run your tests

      - name: Deploy to Azure
        run: |
          az functionapp deployment source config-zip \
            --resource-group <YOUR_RESOURCE_GROUP> \
            --name <YOUR_FUNCTION_APP_NAME> \
            --src <PATH_TO_ZIP_FILE>  # Path to your zipped application
