name: CI/CD Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Azure Storage
      run: |
        az storage blob upload-batch -d '$web' -s './Frontend' --account-name waqasstorage

    - name: Rename index file
      run: |
        az storage blob copy start --source-blob index3.html --destination-blob index.html --destination-container '$web' --account-name waqasstorage
