name: Deploy Azure Functions

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python (or your language)  
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version here

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Adjust based on your project

      - name: Deploy to Azure Functions
        uses: azure/functions-action@v1
        with:
          app-name: WAQASCanadaCentral        
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}  
          package: '.'
