name: CI/CD Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build website
      run: npm run build

    - name: Deploy to Azure Storage
      run: |
        az storage blob upload-batch -d '$web' -s './Frontend' --account-name waqasstorage

    - name: Rename index file
      run: |
        az storage blob copy start --source-blob index3.html --destination-blob index.html --destination-container '$web' --account-name waqasstorage
